apiVersion: v1
kind: Service
metadata:
  labels:
    db: influxdb
  name: rethinkdb-admin
spec:
  ports:
   - port: 8080
     targetPort: 8080
  type: LoadBalancer
  selector:
    db: rethinkdb
    role: admin
