
FROM    golang:1.5
RUN     mkdir -p /tmp/godep && \
        GOPATH=/tmp/godep go get github.com/tools/godep && \
        mv /tmp/godep/bin/godep /usr/local/bin/godep && \
        rm -rf /tmp/godep

WORKDIR /go/src/github.com/docker/swarm

ENV     CGO_ENABLED=0

CMD     godep go install -v -a \
            -tags netgo \
            -installsuffix netgo \
            -ldflags "-w -X github.com/docker/swarm/version.GITCOMMIT=$VERSION"
