options:
  version:
    type: string
    default: "v1.0.0"
    description: |
        The kubernetes release to use in this charm. The binary files are
        compiled from the source identified by this tag in github. Using the
        value of "source" will use the master kubernetes branch when compiling
        the binaries.
  username:
    type: string
    default: "admin"
    description: |
        The initial user for the kubernetes basic authentication file.
  password:
    type: string
    default: ""
    description: |
        The password for the kubernetes basic authentication.  If this value is
        empty, a password will be generated at random for the username.
  apiserver-cert:
    type: string
    default: ""
    description: |
        The ssl certificate to use for tls communication to the Kubernetes api
        server.  If this value is empty a self signed certificate and key will
        be generated.
  apiserver-key:
    type: string
    default: ""
    description: |
        The private key to use for tls communication to the Kubernetes api
        server.  If this value is empty a key and certificate will be generated.
