language: go

go:
  - 1.4
  - 1.3

install:
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  - go test -cover ./...

notifications:
  email: false
