apiVersion: v1
kind: ReplicationController
metadata:
  name: monitoring-influxdb-grafana-v2
  namespace: kube-system
  labels: 
    k8s-app: influxGrafana
    version: v2
    kubernetes.io/cluster-service: "true"
spec: 
  replicas: 1
  selector: 
    k8s-app: influxGrafana
    version: v2
  template: 
    metadata: 
      labels: 
        k8s-app: influxGrafana
        version: v2
        kubernetes.io/cluster-service: "true"
    spec: 
      containers: 
        - image: gcr.io/google_containers/heapster_influxdb:v0.4
          name: influxdb
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
          ports: 
            - containerPort: 8083
              hostPort: 8083
            - containerPort: 8086
              hostPort: 8086
          volumeMounts:
          - name: influxdb-persistent-storage
            mountPath: /data
        - image: grafana/grafana:2.1.0
          name: grafana
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: "GF_AUTH_BASIC_ENABLED"
              value: "false"
            - name: "GF_AUTH_ANONYMOUS_ENABLED"
              value: "true"
            - name: "GF_AUTH_ANONYMOUS_ORG_ROLE"
              value: "Admin"
            - name: "GF_SERVER_ROOT_URL"
              value: "/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/"
          volumeMounts:
          - name: grafana-persistent-storage
            mountPath: /var

              
      volumes:
      - name: influxdb-persistent-storage
        emptyDir: {}
      - name: grafana-persistent-storage
        emptyDir: {}


