apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: skydns
  name: skydns
  namespace: kube-system
spec:
  portalIP: ${DNS_SERVER_IP}
  ports:
  - port: 53
    protocol: UDP
    targetPort: 53
  selector:
    k8s-app: skydns
