kind: ReplicationController
apiVersion: v1
metadata:
  name: etcd-discovery
  creationTimestamp: 
spec:
  strategy:
    type: Recreate
    resources: {}
  triggers:
  - type: ConfigChange
  replicas: 1
  selector:
    name: etcd-discovery
  template:
    metadata:
      creationTimestamp: 
      labels:
        name: etcd-discovery
    spec:
      containers:
      - name: discovery
        image: openshift/etcd-20-centos7
        args:
        - etcd-discovery.sh
        ports:
        - containerPort: 2379
          protocol: TCP
        resources: {}
        terminationMessagePath: "/dev/termination-log"
        imagePullPolicy: IfNotPresent
        capabilities: {}
        securityContext:
          capabilities: {}
          privileged: false
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      serviceAccount: ''
status: {}
