## This file is used as input to deployment script, which amends it as needed.
## More specifically, we need to add peer hosts for each but the elected peer.

coreos:
  units:
    - name: etcd2.service
      enable: true
      command: start
  etcd2:
    name: '%H'
    initial-cluster-token: 'etcd-cluster'
    initial-advertise-peer-urls: 'http://%H:2380'
    listen-peer-urls: 'http://%H:2380'
    listen-client-urls: 'http://0.0.0.0:2379,http://0.0.0.0:4001'
    advertise-client-urls: 'http://%H:2379,http://%H:4001'
    initial-cluster-state: 'new'
  update:
    group: stable
    reboot-strategy: off
