// Code generated by protoc-gen-gogo.
// source: proto.proto
// DO NOT EDIT!

/*
Package importdedup is a generated protocol buffer package.

It is generated from these files:
	proto.proto

It has these top-level messages:
	Object
*/
package importdedup

import proto "github.com/gogo/protobuf/proto"
import math "math"

// discarding unused import gogoproto "github.com/gogo/protobuf/gogoproto"
import subpkg "github.com/gogo/protobuf/test/importdedup/subpkg"

import github_com_gogo_protobuf_test_importdedup_subpkg "github.com/gogo/protobuf/test/importdedup/subpkg"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Object struct {
	CustomField      *github_com_gogo_protobuf_test_importdedup_subpkg.CustomType `protobuf:"bytes,1,opt,customtype=github.com/gogo/protobuf/test/importdedup/subpkg.CustomType" json:"CustomField,omitempty"`
	SubObject        *subpkg.SubObject                                            `protobuf:"bytes,2,opt" json:"SubObject,omitempty"`
	XXX_unrecognized []byte                                                       `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}

func (m *Object) GetSubObject() *subpkg.SubObject {
	if m != nil {
		return m.SubObject
	}
	return nil
}
