name: kubernetes
summary: Container Cluster Management Node
maintainers:
    - Matt Bruzek <matthew.bruzek@canonical.com>
    - Whit Morriss <whit.morriss@canonical.com>
    - Charles Butler <charles.butler@canonical.com>
description: |
  Provides a kubernetes node for running containers
  See http://goo.gl/CSggxE
tags:
    - ops
    - network
subordinate: true
requires:
  etcd:
    interface: etcd
  api:
    interface: kubernetes-api
  network:
    interface: overlay-network
  docker-host:
    interface: juju-info
    scope: container
